### ISSUE TITLE
Quaternion is 0 in "/nuscenes/bboxes"

### ISSUE THREAD

**Issue by rayee-github** [Owen-Liuyuxuan/nuscenes_visualize#1]
This is the output data of /nuscenes/bboxes, we can see the quaternion are all 0.
![Screenshot from 2023-09-21 14-32-12](https://github.com/Owen-Liuyuxuan/nuscenes_visualize/assets/32994498/cf732636-6727-47f7-9fa7-ce7b34cee7f4)
It's working fine in ros1 rviz, but if convert it to ros2 format, ros2 rviz2 will show a wrong angle.
![Screenshot from 2023-09-21 14-44-23](https://github.com/Owen-Liuyuxuan/nuscenes_visualize/assets/32994498/7e22c281-9bfe-49ba-838e-e119d86e11fd)
It can easy be corrected in ros_util.py, such as:
![Screenshot from 2023-09-21 14-45-37](https://github.com/Owen-Liuyuxuan/nuscenes_visualize/assets/32994498/df57d057-778f-465b-a1a7-66e8124e4431)

**Comment by Owen-Liuyuxuan** [comment]
Thanks a lot, I have not tried running this code directly on ros2 rviz2. If it helps I could add this code.

Recently, I have been working on making a separate repo for building/running everything on ROS2. I hope that could help you.

**Comment by Owen-Liuyuxuan** [comment]
@rayee-github 
You could try out this https://github.com/Owen-Liuyuxuan/ros2_dataset_bridge If that's necessary

**Comment by Owen-Liuyuxuan** [comment]
Fixed
https://github.com/Owen-Liuyuxuan/nuscenes_visualize/commit/85bd068a678d84fe0b71d515be71c11236eef1e4
